#ifndef HBSVG_CH_
#define HBSVG_CH_

#define FONT_WEIGHT_THIN        100
#define FONT_WEIGHT_EXTRA_LIGHT 200
#define FONT_WEIGHT_LIGHT       300
#define FONT_WEIGHT_NORMAL      400
#define FONT_WEIGHT_MEDIUM      500
#define FONT_WEIGHT_SEMI_BOLD   600
#define FONT_WEIGHT_BOLD        700
#define FONT_WEIGHT_EXTRA_BOLD  800
#define FONT_WEIGHT_BLACK       900

#endif /* HBSVG_H_ */